In [1]:
import numpy as np

In [4]:
#Create a null vector of size 10 but the fifth value which is 1
a=np.zeros(10)
a[4]=1

print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#Create a vector with values ranging from 10 to 49
b=np.random.randint(10,50, size=10)

print(b)

[24 12 42 37 44 47 49 31 27 16]


In [24]:
#Reverse a vector (first element becomes last)
c=np.array((1,5,10))
c=c[::-1]

print(c)

[10  5  1]


In [25]:
#Create a 3x3 matrix with values ranging from 0 to 8
d=np.random.randint(0,9, (3,3))

print(d)

[[7 1 5]
 [0 4 8]
 [2 8 3]]


In [31]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
e=np.array([1,2,0,0,4,0])
ie=np.where(e!=0)

print(ie)

(array([0, 1, 4]),)


In [36]:
#Create a random vector of size 30 and find the mean value
f=np.random.rand(30)
mf=np.mean(f)

print(mf)

0.4965395709896475


In [43]:
#Create a 2d array with 1 on the border and 0 inside
g=np.ones((5,5))
g[1:-1,1:-1]=0;

print(g)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
h=np.zeros((8,8))
h[1::2,0::2]=1;
h[0::2,1::2]=1;

print(h)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [71]:
#Create a checkerboard 8x8 matrix using the tile function
i=np.tile(h,(8,8))

print(i)

[[0. 1. 0. ... 1. 0. 1.]
 [1. 0. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 1.]
 ...
 [1. 0. 1. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 1.]
 [1. 0. 1. ... 0. 1. 0.]]


In [97]:
#Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z=np.where((Z>2)&(Z<9),Z*-1,Z)

print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [100]:
# Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.08010147 0.14207644 0.32521184 0.50348789 0.51062331 0.52875453
 0.62198626 0.783942   0.87392731 0.95912956]


In [104]:
#Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal=np.equal(A,B)
print(equal)

[False  True  True  True False]


In [114]:
#How to convert an integer (32 bits) array into a float (32 bits) in place?
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = np.arange(10,dtype=np.float32)
print(Z.dtype)

int32
float32


In [119]:
#How to get the diagonal of a dot product?
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diagonal(C)
print(D)

[ 18  66 132]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
