In [1]:
import numpy as np

In [2]:
# Program to multiply two matrices using nested loops
import random

In [3]:
N = 5

In [4]:
# NxN matrix
X = []
for i in range(N):
    X.append([random.randint(0,100) for r in range(N)])
print(len(X))
print(len(X[0]))
print(X)

5
5
[[27, 32, 6, 25, 11], [91, 69, 79, 79, 41], [21, 44, 87, 39, 76], [6, 54, 71, 62, 18], [65, 13, 26, 31, 100]]


In [5]:
Xn=np.random.randint(0,100, (N,N))
print(Xn.shape)
print(Xn)

(5, 5)
[[86  9 55 60 97]
 [50 76 38 47 67]
 [60 84 79  1 97]
 [ 4 25 71 18 44]
 [12  7 20 83 49]]


In [6]:
# Nx(N+1) matrix
Y = []
for i in range(N):
    Y.append([random.randint(0,100) for r in range(N+1)])
print(len(Y))
print(len(Y[0]))
print(Y)

5
6
[[30, 95, 44, 20, 99, 15], [26, 43, 81, 54, 41, 31], [15, 48, 69, 41, 8, 3], [52, 13, 74, 23, 64, 74], [59, 80, 38, 15, 34, 21]]


In [7]:
Yn=np.random.randint(0,100, (N,N+1))
print(Yn.shape)
print(Yn)

(5, 6)
[[39 90 38 77 39 35]
 [86 36 95 78 89 60]
 [73  5 72 45 42 92]
 [81 99 45 96 81 16]
 [46 89 61 34 19 46]]


In [8]:
# result is Nx(N+1)
result = []
for i in range(N):
    result.append([0] * (N+1))
    
print(len(result))
print(len(result[0]))

5
6


In [9]:
#resultn=np.zeros((N,N+1))
#print(resultn.shape)

In [10]:
# iterate through rows of X
for i in range(len(X)):
    # iterate through columns of Y
    for j in range(len(Y[0])):
        # iterate through rows of Y
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)
    
print(len(result))
print(len(result[0]))   

[3681, 5434, 6462, 3254, 6007, 3496]
[12236, 19711, 22448, 11217, 18920, 10448]
[9591, 14650, 16265, 8400, 9659, 6422]
[6935, 8546, 14809, 7643, 7956, 6943]
[10190, 16385, 11801, 5281, 12560, 5850]
5
6


In [11]:
resultn=np.matmul(Xn,Yn);
print(resultn)
print(resultn.shape)

[[17465 22912 16700 18857 13168 14032]
 [18149 18042 18058 18278 15390 13640]
 [19874 17551 21910 18121 15058 18886]
 [10971  7313 11133  8677  7657 10484]
 [11507 14010  9285 12004  9585  6262]]
(5, 6)
